### ISSUE TITLE
Broken subgraph

### ISSUE THREAD

**Issue by deantheiceman** [pancakeswap/pancake-v2-subgraph#3]
The subgraph on https://pancakeswap.info/ is out of date and deploying my own local version is always out of sync. Any ideas?

**Comment by ChefKai** [comment]
Hello, the syncing process can be quite long as you can tell; the subgraph is not actually broken but it needs to process each block (~4.5M blocks since we started PancakeSwap), and each transaction one by one in order to be able to provide meaningful statistics. That said, you can estimate the amount of data servers and your local machine have to process.
