### ISSUE TITLE
Empty swaps

### ISSUE THREAD

**Issue by SametAylak** [pancakeswap/pancake-v2-subgraph#6]
I deployed this subgraph to thegraph.com but when I query for swaps, it returns empty array. You can find related links below;

https://thegraph.com/explorer/subgraph/sametaylak/pancakeswapv2

Btw, It says `Synced 11,933,330 blocks`? Any ideas?

**Comment by ChefKai** [comment]
TheGraph does not support Binance Smart Chain to index subgraphs; you can tell it's not deployed with the right blockchain because of the block height.

To get an accurate dataset, you have to setup a graph node (you can use Docker, [example](https://github.com/graphprotocol/graph-node/blob/master/docker/docker-compose.yml)) linked to a BSC archive node (can use public RPC - but there is rate limit - or setup your own in local) then you can deploy it and sync.

**Comment by SametAylak** [comment]
How can I use public RPC or how can I setup a graph node and bind it? Is there any documentation that you can share with me? I am kind a new for this stuff

**Comment by SametAylak** [comment]
Oh, I think I got you. I need to simply change `graph deploy sametaylak/pancakeswapv2 --ipfs MY_IPFS_ADDRESS --node MY_NODE_ADDRES --debug`, right?

**Comment by SametAylak** [comment]
Thanks for your interest. I found an another solution with using web3 events.
